### PR TITLE
Adds the Ruby rack application resource.

### PR DESCRIPTION
**Pull request by johnbellone**

### CODE REVIEW

**Comment by coderanger** [comment]
This seems oddly specific. What's the use case over the existing integrations?

**Comment by johnbellone** [comment]
We're using the [Grape API](https://github.com/ruby-grape/grape).

**Comment by coderanger** [comment]
Okay, but you set this up as a service resource even though there is no service, it isn't particularly related to rack, and it is probably better served by a single `ruby_execute` resource?

**Comment by johnbellone** [comment]
@coderanger Sorry, it looks like this may be better served as the dotenv being a new sub-resource. This deploy exactly like a Sinatra application.

**Pull request closed without merging**
